apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'

group = 'com.xdtmaker.feishulogin'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useDefaultAndroidSdkVersions()

android {
  namespace "com.xdtmaker.feishulogin"

  defaultConfig {
    minSdkVersion 23
  }
}

repositories {
  flatDir {
    dirs 'libs'
  }
}

dependencies {
  api(name: 'larksso-3.0.10', ext: 'aar')
}
