// 自动从 2026-07-17-cindy-token-decision-table.md 提取(U8 批准冻结值)。
// D2T 八组断言 + 零残留脚本共享的决策基线;手改 cindy 主题值时此处不变 → 测试抓漂移。
// 不要手编此文件;改值请先过用户关卡再更新决策表 + 重生成。

export const CINDY_REQUIRED_COLOR_IDS = [
  'surface',
  'surface-hsl',
  'surface-elevated',
  'surface-elevated-soft',
  'surface-card-ivory',
  'surface-chip',
  'surface-chip-alt',
  'surface-hover',
  'surface-hover-soft',
  'surface-hover-hsl',
  'surface-on-card',
  'border-default',
  'border-default-hsl',
  'border-shadcn-hsl',
  'border-transparent-mixed',
  'text-primary',
  'text-primary-on-dark',
  'text-primary-emphasis',
  'text-primary-inv',
  'text-primary-body-strong',
  'text-primary-hsl',
  'text-secondary',
  'text-secondary-cross',
  'text-secondary-mid',
  'text-tertiary',
  'text-tertiary-stone',
  'text-tertiary-mid',
  'text-tertiary-hsl',
  'text-disabled',
  'text-disabled-tertiary',
  'accent-cta-bg',
  'accent-cta-bg-pure',
  'accent-emphasis',
  'accent-soft',
  'accent-hover',
  'accent-pure-cta-fg',
  'accent',
  'agent-actions-rail',
  'ask-checkbox-border',
  'background',
  'chat-input-bg',
  'chat-input-chip-border',
  'chat-input-text',
  'color-primary',
  'confirm-bg',
  'confirm-btn-primary-bg',
  'confirm-btn-primary-text',
  'confirm-btn-secondary-border',
  'confirm-btn-secondary-hover',
  'confirm-btn-secondary-text',
  'confirm-title',
  'drop-overlay-bg',
  'file-chip-bg',
  'file-remove-bg',
  'info-700',
  'migration-bar-fill',
  'migration-bar-track',
  'model-trigger-hover',
  'msg-link',
  'msg-scrollbar-hover',
  'msg-user-bg',
  'muted',
  'muted-foreground',
  'perm-auto-selected-text',
  'perm-allow-btn-bg',
  'perm-allow-btn-text',
  'perm-allow-kbd-bg',
  'perm-allow-kbd-border',
  'perm-code-bg',
  'perm-item-selected-bg',
  'plan-outline-active-bg',
  'plan-toolbar-btn-hover-bg',
  'popover',
  'primary-foreground',
  'search-match-fg',
  'secondary',
  'settings-btn-primary-text',
  'settings-btn-secondary-hover-bg',
  'text-placeholder',
  'settings-integration-avatar-bg',
  'settings-logout-bg',
  'settings-menu-bg-hover',
  'settings-menu-bg-selected',
  'settings-source-link',
  'settings-theme-auto-dark',
  'sidebar-action-icon',
  'sidebar-item-active',
  'splash-bg',
  'splash-text',
  'splash-text-destructive',
  'splash-text-muted',
  'titlebar-icon',
  'tooltip-bg',
  'tooltip-text',
  'update-btn-border',
  'update-btn-text',
  'accent-foreground',
  'panel-bg',
  'primary',
  'ring',
  'settings-theme-auto-light',
  'foreground',
  'border',
  'input',
  'secondary-foreground',
  'popover-foreground',
  'titlebar',
  'titlebar-border',
  'titlebar-button-hover',
  'titlebar-control-hover',
  'sidebar',
  'sidebar-border',
  'sidebar-item-hover',
  'sidebar-search-bg',
  'sidebar-muted',
  'status-badge-fg', // D2 期新增,值经队列震荡后按 HEAD 冻结(#1F1F1F,5.61:1 × #FF6600 ≥4.5),批准依据:用户亲批方案 2026-07-17,115→116
] as const;

export const HSL_FORMAT_IDS = [
  'surface-hsl',
  'surface-hover-hsl',
  'border-default-hsl',
  'border-shadcn-hsl',
  'text-primary-hsl',
  'text-tertiary-hsl',
  'background',
  'foreground',
  'muted',
  'muted-foreground',
  'border',
  'input',
  'ring',
  'primary',
  'primary-foreground',
  'secondary',
  'secondary-foreground',
  'accent',
  'accent-foreground',
  'popover',
  'popover-foreground',
  'titlebar',
  'titlebar-border',
  'titlebar-icon',
  'titlebar-button-hover',
  'titlebar-control-hover',
  'splash-bg',
  'splash-text',
  'splash-text-muted',
  'splash-text-destructive',
  'destructive',
  'sidebar',
  'sidebar-border',
  'sidebar-item-hover',
  'sidebar-item-active',
  'sidebar-search-bg',
  'sidebar-muted',
  'sidebar-action-icon',
  'search-match-bg',
  'search-match-fg',
  'content-area',
  'welcome-text',
] as const;

export const CINDY_EXPECTED_VALUES: Record<string, { light: string; dark: string }> = {
  surface: { light: '#EDEDED', dark: '#2A2828' },
  'surface-hsl': { light: '0.0 0.0% 92.9%', dark: '0.0 2.4% 16.1%' },
  'surface-elevated': { light: '#F8F8F8', dark: '#312F2F' },
  'surface-elevated-soft': { light: '#F4F4F4', dark: '#2F2D2D' },
  'surface-card-ivory': { light: '#F8F8F8', dark: '#312F2F' },
  'surface-chip': { light: '#F1F1F1', dark: '#2F2D2D' },
  'surface-chip-alt': { light: '#F4F4F4', dark: '#2F2D2D' },
  'surface-hover': { light: '#F1F1F1', dark: '#2F2D2D' },
  'surface-hover-soft': { light: '#EFEFEF', dark: '#2B2929' },
  'surface-hover-hsl': { light: '0.0 0.0% 94.5%', dark: '0.0 2.2% 18.0%' },
  'surface-on-card': { light: '#FFFFFF', dark: '#2A2828' },
  'border-default': { light: '#DCDFE3', dark: '#434343' },
  'border-default-hsl': { light: '214.3 11.1% 87.6%', dark: '0.0 0.0% 26.3%' },
  'border-shadcn-hsl': { light: '214.3 11.1% 87.6%', dark: '0.0 0.0% 26.3%' },
  'border-transparent-mixed': { light: 'transparent', dark: '#434343' },
  'text-primary': { light: '#3C3F43', dark: '#D4D4D4' },
  'text-primary-on-dark': { light: '#FFFFFF', dark: '#FFFFFF' },
  'text-primary-emphasis': { light: '#2E3237', dark: '#FFFFFF' },
  'text-primary-inv': { light: '#FFFFFF', dark: '#2A2828' },
  'text-primary-body-strong': { light: '#3C3F43', dark: '#D4D4D4' },
  'text-primary-hsl': { light: '214.3 5.5% 24.9%', dark: '0.0 0.0% 83.1%' },
  'text-secondary': { light: '#9A9DA3', dark: '#6F6F6F' },
  'text-secondary-cross': { light: '#9A9DA3', dark: '#6F6F6F' },
  'text-secondary-mid': { light: '#686B72', dark: '#BFC1C4' },
  'text-tertiary': { light: '#686B72', dark: '#BFC1C4' },
  'text-tertiary-stone': { light: '#686B72', dark: '#BFC1C4' },
  'text-tertiary-mid': { light: '#686B72', dark: '#BFC1C4' },
  'text-tertiary-hsl': { light: '222.0 4.6% 42.7%', dark: '216.0 4.1% 75.9%' },
  'text-disabled': { light: '#686B72', dark: '#BFC1C4' },
  'text-disabled-tertiary': { light: '#686B72', dark: '#BFC1C4' },
  'accent-cta-bg': { light: '#DF0C27', dark: '#DF0C27' },
  'accent-cta-bg-pure': { light: '#DF0C27', dark: '#DF0C27' },
  'accent-emphasis': { light: '#DF0C27', dark: '#DF0C27' },
  'accent-soft': { light: '#A61629', dark: '#A61629' },
  'accent-hover': { light: '#A61629', dark: '#A61629' },
  'accent-pure-cta-fg': { light: '#FFFFFF', dark: '#FFFFFF' },
  accent: { light: '0.0 0.0% 94.5%', dark: '0.0 2.2% 18.0%' },
  'agent-actions-rail': { light: '#DCDFE3', dark: '#434343' },
  'ask-checkbox-border': { light: '#686B72', dark: '#BFC1C4' },
  background: { light: '0.0 0.0% 92.9%', dark: '0.0 2.4% 16.1%' },
  'chat-input-bg': { light: '#F8F8F8', dark: '#312F2F' },
  'chat-input-chip-border': { light: '#DCDFE3', dark: '#434343' },
  'chat-input-text': { light: '#3C3F43', dark: '#D4D4D4' },
  'color-primary': { light: '#3C3F43', dark: '#D4D4D4' },
  'confirm-bg': { light: '#F8F8F8', dark: '#312F2F' },
  'confirm-btn-primary-bg': { light: '#DF0C27', dark: '#DF0C27' },
  'confirm-btn-primary-text': { light: '#FFFFFF', dark: '#FFFFFF' },
  'confirm-btn-secondary-border': { light: '#DCDFE3', dark: '#434343' },
  'confirm-btn-secondary-hover': { light: 'rgba(0, 0, 0, 0.06)', dark: 'rgba(255, 255, 255, 0.08)' },
  'confirm-btn-secondary-text': { light: '#3C3F43', dark: '#D4D4D4' },
  'confirm-title': { light: '#3C3F43', dark: '#D4D4D4' },
  'drop-overlay-bg': { light: 'rgba(223, 12, 39, 0.10)', dark: 'rgba(223, 12, 39, 0.10)' },
  'file-chip-bg': { light: '#D8D9DB', dark: '#3B3A3A' },
  'file-remove-bg': { light: '#686B72', dark: '#BFC1C4' },
  'info-700': { light: '#1D4ED8', dark: '#93C5FD' },
  'migration-bar-fill': { light: '#DF0C27', dark: '#DF0C27' },
  'migration-bar-track': { light: '#F1F1F1', dark: '#2F2D2D' },
  'model-trigger-hover': { light: '#F1F1F1', dark: '#2F2D2D' },
  'msg-link': { light: '#1D4ED8', dark: '#93C5FD' },
  'msg-scrollbar-hover': { light: '#D8D9DB', dark: '#504F4F' },
  'msg-user-bg': { light: '#F8F8F8', dark: '#312F2F' },
  muted: { light: '0.0 0.0% 94.5%', dark: '0.0 2.2% 18.0%' },
  'muted-foreground': { light: '222.0 4.6% 42.7%', dark: '216.0 4.1% 75.9%' },
  'perm-auto-selected-text': { light: '#1D4ED8', dark: '#00D9C5' },
  'perm-allow-btn-bg': { light: '#DF0C27', dark: '#DF0C27' },
  'perm-allow-btn-text': { light: '#FFFFFF', dark: '#FFFFFF' },
  'perm-allow-kbd-bg': { light: '#F4F4F4', dark: '#2F2D2D' },
  'perm-allow-kbd-border': { light: '#DCDFE3', dark: '#434343' },
  'perm-code-bg': { light: '#F5F5F5', dark: '#2B2929' },
  'perm-item-selected-bg': { light: '#F1F1F1', dark: '#2F2D2D' },
  'plan-outline-active-bg': { light: '#F1F1F1', dark: '#2F2D2D' },
  'plan-toolbar-btn-hover-bg': { light: '#F1F1F1', dark: '#2F2D2D' },
  popover: { light: '0.0 0.0% 97.3%', dark: '0.0 2.1% 18.8%' },
  'primary-foreground': { light: '0.0 0.0% 100.0%', dark: '0.0 0.0% 100.0%' },
  'search-match-fg': { light: '214.3 5.5% 24.9%', dark: '0.0 0.0% 83.1%' },
  secondary: { light: '0.0 0.0% 94.5%', dark: '0.0 2.2% 18.0%' },
  'settings-btn-primary-text': { light: '#FFFFFF', dark: '#FFFFFF' },
  'settings-btn-secondary-hover-bg': { light: '#F1F1F1', dark: '#2F2D2D' },
  'text-placeholder': { light: '#686B72', dark: '#BFC1C4' },
  'settings-integration-avatar-bg': { light: '#F8F8F8', dark: '#2F2D2D' },
  'settings-logout-bg': { light: '#F8F8F8', dark: '#312F2F' },
  'settings-menu-bg-hover': { light: '#EFEFEF', dark: '#2B2929' },
  'settings-menu-bg-selected': { light: '#F1F1F1', dark: '#2F2D2D' },
  'settings-source-link': { light: '#1D4ED8', dark: '#93C5FD' },
  'settings-theme-auto-dark': { light: '#2A2828', dark: '#2A2828' },
  'sidebar-action-icon': { light: '222.0 4.6% 42.7%', dark: '216.0 4.1% 75.9%' },
  'sidebar-item-active': { light: '352.3 89.8% 46.1%', dark: '352.3 89.8% 46.1%' },
  'splash-bg': { light: '0.0 0.0% 92.9%', dark: '0.0 2.4% 16.1%' },
  'splash-text': { light: '222.0 4.6% 42.7%', dark: '216.0 4.1% 75.9%' },
  'splash-text-destructive': { light: '214.3 5.5% 24.9%', dark: '0.0 0.0% 100.0%' },
  'splash-text-muted': { light: '222.0 4.6% 42.7%', dark: '216.0 4.1% 75.9%' },
  'titlebar-icon': { light: '222.0 4.6% 42.7%', dark: '216.0 4.1% 75.9%' },
  'tooltip-bg': { light: '#3C3F43', dark: '#2A2828' },
  'tooltip-text': { light: '#FFFFFF', dark: '#FFFFFF' },
  'update-btn-border': { light: '#DF0C27', dark: '#DF0C27' },
  'update-btn-text': { light: '#DF0C27', dark: '#DF0C27' },
  'accent-foreground': { light: '214.3 5.5% 24.9%', dark: '0.0 0.0% 83.1%' },
  'panel-bg': { light: '#EDEDED', dark: '#2A2828' },
  primary: { light: '352.3 89.8% 46.1%', dark: '352.3 89.8% 46.1%' },
  ring: { light: '217.2 91.2% 59.8%', dark: '217.2 91.2% 59.8%' },
  'settings-theme-auto-light': { light: '#EDEDED', dark: '#EDEDED' },
  foreground: { light: '214.3 5.5% 24.9%', dark: '0.0 0.0% 83.1%' },
  border: { light: '214.3 11.1% 87.6%', dark: '0.0 0.0% 26.3%' },
  input: { light: '214.3 11.1% 87.6%', dark: '0.0 0.0% 26.3%' },
  'secondary-foreground': { light: '214.3 5.5% 24.9%', dark: '0.0 0.0% 83.1%' },
  'popover-foreground': { light: '214.3 5.5% 24.9%', dark: '0.0 0.0% 83.1%' },
  titlebar: { light: '0.0 0.0% 92.9%', dark: '0.0 2.4% 16.1%' },
  'titlebar-border': { light: '214.3 11.1% 87.6%', dark: '0.0 0.0% 26.3%' },
  'titlebar-button-hover': { light: '0.0 0.0% 94.5%', dark: '0.0 2.2% 18.0%' },
  'titlebar-control-hover': { light: '0.0 0.0% 94.5%', dark: '0.0 2.2% 18.0%' },
  sidebar: { light: '0.0 0.0% 92.9%', dark: '0.0 2.4% 16.1%' },
  'sidebar-border': { light: '214.3 11.1% 87.6%', dark: '0.0 0.0% 26.3%' },
  'sidebar-item-hover': { light: '0.0 0.0% 94.5%', dark: '0.0 2.2% 18.0%' },
  'sidebar-search-bg': { light: '0.0 0.0% 92.9%', dark: '0.0 2.4% 16.1%' },
  'sidebar-muted': { light: '222.0 4.6% 42.7%', dark: '216.0 4.1% 75.9%' },
  'status-badge-fg': { light: '#1F1F1F', dark: '#1F1F1F' }, // §7 必炸点(lead 裁决)
};

export const BRAND_RED_EXPECTED_BY_ID: Record<string, string> = {
  'accent-cta-bg': '#DF0C27',
  'accent-cta-bg-pure': '#DF0C27',
  'accent-emphasis': '#DF0C27',
  'confirm-btn-primary-bg': '#DF0C27',
  'migration-bar-fill': '#DF0C27',
  'perm-allow-btn-bg': '#DF0C27',
  'primary': '352.3 89.8% 46.1%',
  'sidebar-item-active': '352.3 89.8% 46.1%',
  'update-btn-border': '#DF0C27',
  'update-btn-text': '#DF0C27',
};

export const BRAND_RED_ALLOWED_IDS = [
  'accent-cta-bg',
  'accent-cta-bg-pure',
  'accent-emphasis',
  'confirm-btn-primary-bg',
  'migration-bar-fill',
  'perm-allow-btn-bg',
  'primary',
  'sidebar-item-active',
  'update-btn-border',
  'update-btn-text',
  'accent-soft',
  'accent-hover',
  'drop-overlay-bg',
  'confirm-btn-primary-hover',
  'settings-btn-primary-bg',
  'settings-btn-primary-border',
  'settings-btn-primary-hover-bg',
] as const;

export const CTA_FOREGROUND_WHITE_IDS = [
  'accent-pure-cta-fg',
  'confirm-btn-primary-text',
  'perm-allow-btn-text',
  'primary-foreground',
  'settings-btn-primary-text',
] as const;
