import path from 'node:path';
import { fileURLToPath } from 'node:url';

export function printHelp(log = console.log) {
  log('\n  Cindy 客户端仓常用指令（按场景分组，可直接复制）');

  log('\n  桌面端启动（以下命令可直接复制）:');
  log('    # 推荐：先清理已有 Cindy dev 进程，再启动远程 API 模式');
  log('    pnpm restart:desktop:remote --region=cn');
  log('      国内版，读取仓内 config/endpoint.json');
  log('    pnpm restart:desktop:remote --region=global');
  log('      海外版，读取仓内 config/endpoint.global.json');
  log('    pnpm restart:desktop:remote --region=global --endpoints-cdn');
  log('      海外版，读取对应区域的线上 CDN 端点清单');
  log('    # Human 可直接启动；不会先清旧进程，Agent 不要使用');
  log('    pnpm dev:desktop:remote --region=cn');
  log('    pnpm dev:desktop:remote --region=global');
  log('    # 连接本地 http://localhost:3333（只起客户端，不起 server）');
  log('    pnpm restart:desktop:local --region=cn');

  log('\n  桌面端只打包、不上传 OSS/CDN（以下命令可直接复制）:');
  log('    pnpm package:desktop -- --region cn --channel dev');
  log('      当前平台，国内版，版本无关开发包');
  log('    pnpm package:desktop -- --region global --channel dev');
  log('      当前平台，海外版，版本无关开发包');
  log('    pnpm package:mac:arm64 -- --region cn --channel dev');
  log('    pnpm package:mac:x64 -- --region cn --channel dev');
  log('    pnpm package:win -- --region cn --channel dev');
  log('    pnpm package:linux -- --region cn --channel dev');
  log('    pnpm package:desktop -- --region cn --channel release --version patch');
  log('      当前平台，国内 release 包；基于 CDN 当前版本自动 bump patch');
  log('    pnpm package:desktop -- --region global --channel release --version patch');
  log('      当前平台，海外 release 包；基于 CDN 当前版本自动 bump patch');
  log('    # 调试时可在末尾追加 --skip-smoke；明确允许无签名时追加 --allow-unsigned');

  log('\n  桌面端旧版打包 + 发布一体流程（直接上传 canary）:');
  log('    pnpm release:mac');
  log('    pnpm release:win');
  log('    pnpm release:linux');
  log('    # 强制用户更新后重新授权飞书');
  log('    pnpm release:mac -- --require-relogin');
  log('    pnpm release:win -- --require-relogin');
  log('    # canary 验证后转 stable：先 dry-run，再正式执行');
  log('    pnpm release:promote:mac');
  log('    pnpm release:promote:mac -- --yes');
  log('    pnpm release:promote:win');
  log('    pnpm release:promote:win -- --yes');
  log('    pnpm release:promote:linux');
  log('    pnpm release:promote:linux -- --yes');

  log('\n  Agent 二进制安装 / 升级（Claude Code、Codex、ripgrep）:');
  log('    # 按 latest.json 当前 pin 安装到本机，不修改 pin');
  log('    pnpm install:agent-binaries');
  log('      安装当前平台的全部三种二进制');
  log('    pnpm install:claude');
  log('    pnpm install:codex');
  log('    pnpm install:ripgrep');
  log('      只安装当前平台的指定二进制');
  log('    # 升级到上游最新版：下载全平台二进制，并修改对应 latest.json pin');
  log('    pnpm update:claude');
  log('    pnpm update:codex');
  log('    pnpm update:ripgrep');
  log('    pnpm update:vendors');
  log('      依次把三种二进制全部升级到上游最新版');
  log('    # 固定到指定版本：下面是完整示例，会修改 latest.json pin');
  log('    pnpm update:claude 2.1.199');
  log('    pnpm update:codex 0.144.1');
  log('    pnpm update:ripgrep 15.1.0');

  log('\n  Agent 二进制单独发布（不重新打包 App）:');
  log('    # 先 dry-run：检查全部四个平台，不上传');
  log('    pnpm release:claude-code -- --dry-run');
  log('    pnpm release:codex -- --dry-run');
  log('    pnpm release:ripgrep -- --dry-run');
  log('    # 正式发布：上传全部四个平台，并更新各平台 canary manifest');
  log('    pnpm release:claude-code');
  log('    pnpm release:codex');
  log('    pnpm release:ripgrep');
  log('    # 只发布单个平台');
  log('    pnpm release:claude-code:arm64');
  log('    pnpm release:claude-code:x64');
  log('    pnpm release:claude-code:win');
  log('    pnpm release:claude-code -- --platform linux-x64');
  log('    pnpm release:codex:arm64');
  log('    pnpm release:codex:x64');
  log('    pnpm release:codex:win');
  log('    pnpm release:codex -- --platform linux-x64');
  log('    # Windows Claude/Codex 可显式选择 cn / global / dev 发布目标');
  log('    pnpm release:claude-code:win:cn');
  log('    pnpm release:claude-code:win:global');
  log('    pnpm release:claude-code:win:dev');
  log('    pnpm release:codex:win:cn');
  log('    pnpm release:codex:win:global');
  log('    pnpm release:codex:win:dev');
  log('    pnpm release:ripgrep:arm64');
  log('    pnpm release:ripgrep:x64');
  log('    pnpm release:ripgrep:win');
  log('    pnpm release:ripgrep -- --platform linux-x64');
  log('    # 发布目标：版本化 .gz + manifest-<platform>-canary.json');
  log('      不是独立沙盒目录；canary 用户先看到，stable 用户暂时不受影响');
  log('    # 没有“只 promote 某个二进制”的命令；以下会提升整份平台 manifest');
  log('    pnpm release:promote:mac -- --yes');
  log('    pnpm release:promote:win -- --yes');
  log('    pnpm release:promote:linux -- --yes');

  log('\n  Mobile 本地开发（以下命令可直接复制）:');
  log('    pnpm mobile:xcode');
  log('      国服：生成 iOS 工程、打开 Xcode 并启动 Metro');
  log('    pnpm mobile:xcode --region=global');
  log('      海外版：生成 iOS 工程、打开 Xcode 并启动 Metro');
  log('    pnpm mobile:sim:rebuild');
  log('    pnpm mobile:sim:start');
  log('      国服模拟器：先 rebuild 安装，再 start 启动 Metro');
  log('    pnpm mobile:sim:rebuild -- --region=global');
  log('    pnpm mobile:sim:start -- --region=global');
  log('      海外模拟器：先 rebuild 安装，再 start 启动 Metro');
  log('    pnpm mobile:sim:whoami');
  log('      查看当前 Metro 对应的 checkout / branch');

  log('\n  Mobile EAS / TestFlight（默认 dry-run，--execute 才真正发布）:');
  log('    pnpm mobile:release:check -- --target production');
  log('      检查正式服应走 OTA 还是完整冷更');
  log('    pnpm mobile:release:check -- --target staging');
  log('      检查内部 staging 应走 OTA 还是完整冷更');
  log('    pnpm mobile:release:check -- --target beta --dev dash');
  log('      检查 dash 的手机 Beta 应走 OTA 还是完整冷更');
  log('    pnpm mobile:release:beta -- --dev dash --message "验证本次改动"');
  log('      手机 Beta dry-run');
  log('    pnpm mobile:release:beta -- --dev dash --message "验证本次改动" --execute');
  log('      手机 Beta 正式执行');
  log('    pnpm mobile:release:prod -- --message "发布本次改动"');
  log('      production + staging dry-run（必须在干净且已同步 origin/main 的 main 上）');
  log('    pnpm mobile:release:prod -- --message "发布本次改动" --execute');
  log('      production + staging 正式执行');
  log('    pnpm mobile:beta:add-dev -- alice');
  log('    pnpm mobile:beta:add-dev -- alice --execute');
  log('      新增 alice 的 Beta 配置：先 dry-run，再正式执行');

  log('\n  Mobile 自建 iOS（完整命令；region 必填，无默认值）:');
  log('    pnpm mobile:release:ios:check -- --region cn');
  log('    pnpm mobile:release:ios:local -- --region cn --execute');
  log('    pnpm mobile:release:ios:ota -- --region cn --execute');
  log('    pnpm mobile:release:ios:promote -- --region cn --yes');
  log('      国服：依次对应检查、完整冷更打包发布、JS OTA');
  log('    pnpm mobile:release:ios:check -- --region global');
  log('    pnpm mobile:release:ios:local -- --region global --execute');
  log('    pnpm mobile:release:ios:ota -- --region global --execute');
  log('    pnpm mobile:release:ios:promote -- --region global --yes');
  log('      海外版：依次对应检查、完整冷更打包发布、JS OTA');
  log('      local / ota 先写 canary 指针；promote --yes 验证后才切 stable');
  log('    pnpm mobile:release:ios:npkg -- from-eas');
  log('      手动把最近一次 EAS iOS 产物送 NPKG 重签');

  log('\n  Mobile 自建 Android（完整命令；region 必填，无默认值）:');
  log('    pnpm mobile:release:android:check -- --region cn');
  log('    pnpm mobile:release:android:local -- --region cn --execute');
  log('    pnpm mobile:release:android:ota -- --region cn --execute');
  log('    pnpm mobile:release:android:promote -- --region cn --yes');
  log('      国服：依次对应检查、完整冷更打包发布、JS OTA');
  log('    pnpm mobile:release:android:check -- --region global');
  log('    pnpm mobile:release:android:local -- --region global --execute');
  log('    pnpm mobile:release:android:ota -- --region global --execute');
  log('    pnpm mobile:release:android:promote -- --region global --yes');
  log('      海外版：依次对应检查、完整冷更打包发布、JS OTA');
  log('      local / ota 先写 canary 指针；promote --yes 验证后才切 stable');
  log('    pnpm mobile:release:android:npkg -- upload /absolute/path/Cindy.apk');
  log('      仅在需要时手动补传 APK 到 NPKG，不参与正常冷更链路');

  log('\n  开发检查:');
  log('    pnpm lint');
  log('    pnpm test:runner');
  log('    pnpm test:unit');
  log('    pnpm test:all');
  log('    pnpm test:db');
  log('    pnpm test:guard');
  log();
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  printHelp();
}
