-- 0040_orca_multi_worker_phase1: multi-worker Phase 1 schema 改动(从 GitLab MR !130 迁移)。
--
-- 内容:把 orca_workflows 表/列/索引重命名为 orca_teams / team_id(避免与 Claude Code
-- 官方 Workflow 概念歧义)+ 给 orca_workers 增加 role / focused / idle_since 列 +
-- 重建相关 index + backfill(role 默认 developer、每个 team 首个 worker 标 focused)+
-- 恢复 active team 唯一约束(uniq_active_team_per_lead)。
--
-- 真正的 DDL 全部放到 scripts/0040_orca_multi_worker_phase1.ts 里做 PRAGMA / 目标态守卫式
-- 幂等迁移(沿用 0024 / 0038 / GitLab 原 MR !130 的 0039+0040 脚本模式):rename 走"目标态
-- 检查"、ADD COLUMN 走 table_info 守卫、index 走 IF EXISTS / IF NOT EXISTS。这样全新用户、
-- 已跑过历史中间序号的 dev DB、介于中间的 DB 都收敛到同一最终 schema,且可重复执行。
--
-- drizzle-kit generate 对 rename 只会产出 DROP TABLE + CREATE TABLE(销毁数据、且 INSERT
-- SELECT 引用新列在旧表上不存在会直接报错),因此本 .sql 不用其生成内容,仅占位让自定义
-- migrator 把 schema_version 推到 40,DDL 交给同名 TS 脚本在同一事务内执行。
SELECT 1;
